server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_token1
    username: jwt
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect